//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toprope.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Frontend {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Frontend() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toprope.Resources.Frontend", typeof(Frontend).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the search.
        /// </summary>
        public static string AboutSearch {
            get {
                return ResourceManager.GetString("AboutSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toprope supports plain search queries as well as advanced (parametrized) ones. For example, the query &lt;span class=&quot;code&quot;&gt;hard route&lt;/span&gt; will return all areas, sectors and routes containing the phrase &quot;hard route&quot;. On the other hand, the query &lt;span class=&quot;code&quot;&gt;grade:5.11c-* love&lt;/span&gt; will return all routes harder than 5.11b with the word &quot;love&quot; in the text..
        /// </summary>
        public static string AboutSearch_Body {
            get {
                return ResourceManager.GetString("AboutSearch_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are parameter we currently support:.
        /// </summary>
        public static string AboutSearch_Body2 {
            get {
                return ResourceManager.GetString("AboutSearch_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the author.
        /// </summary>
        public static string AboutTheAuthor {
            get {
                return ResourceManager.GetString("AboutTheAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Toprope.
        /// </summary>
        public static string AboutToprope {
            get {
                return ResourceManager.GetString("AboutToprope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toprope is an easy to use online guidebook for rock climbers. It contains information about climbing areas, sectors and routes from all over the globe. .
        /// </summary>
        public static string AboutToprope_Body {
            get {
                return ResourceManager.GetString("AboutToprope_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the advantages of using Toprope:.
        /// </summary>
        public static string AboutToprope_Body2 {
            get {
                return ResourceManager.GetString("AboutToprope_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toprope was built by &lt;a href=&quot;http://volgarev.me&quot; target=&quot;_blank&quot;&gt;Pavel Volgarev&lt;/a&gt;, a professional web developer and rock climber with more than 7 years of experience in both areas. If you&apos;d like to get in touch, please send me an email to &lt;a href=&quot;mailto:volpav+toprope@gmail.com&quot;&gt;volpav@gmail.com&lt;/a&gt; and I&apos;ll reply as soon as I can..
        /// </summary>
        public static string AboutToprope_Body3 {
            get {
                return ResourceManager.GetString("AboutToprope_Body3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced stuff.
        /// </summary>
        public static string AdvancedStuff {
            get {
                return ResourceManager.GetString("AdvancedStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search queries are case insensitive, meaning that &lt;span class=&quot;code&quot;&gt;Hello World&lt;/span&gt; and &lt;span class=&quot;code&quot;&gt;hello world&lt;/span&gt; will return the same results..
        /// </summary>
        public static string AdvancedStuff_Body {
            get {
                return ResourceManager.GetString("AdvancedStuff_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the parameter value contains spaces, enclose it into double quotes. For example, the query &lt;span class=&quot;code&quot;&gt;name:&quot;Route name&quot;&lt;/span&gt; will return items with names containing the phrase &quot;Route name&quot; whereas the query &lt;span class=&quot;code&quot;&gt;name:Route name&lt;/span&gt; will return items with names containing the word &quot;Route&quot; and having the word &quot;name&quot; in names, descriptions or tags..
        /// </summary>
        public static string AdvancedStuff_Body2 {
            get {
                return ResourceManager.GetString("AdvancedStuff_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters can accept multiple values specified at once. The values in this case must be separated with the comma. For example, the query &lt;span class=&quot;code&quot;&gt;tags:spain,hard-climbing&lt;/span&gt; will return all items with tags &quot;spain&quot; or &quot;hard-climbing&quot;. This technique doesn&apos;t apply when you enclose the parameter value into double quotes (in this case commas are treated as part of the phrase).  .
        /// </summary>
        public static string AdvancedStuff_Body3 {
            get {
                return ResourceManager.GetString("AdvancedStuff_Body3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some parameter allow specifying a range of values. Range bounds are separated with the dash character. If you want to ommit either a lower bound of an upper bound, specify asterisk instead of a value. For example, the query &lt;span class=&quot;code&quot;&gt;grade:5.11a-5.12a&lt;/span&gt; will return all routes that are rated from 5.11a to 5.12a whereas the query &lt;span class=&quot;code&quot;&gt;grade:*-5.13a&lt;/span&gt; will return all routes no harder than 5.13a..
        /// </summary>
        public static string AdvancedStuff_Body4 {
            get {
                return ResourceManager.GetString("AdvancedStuff_Body4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while processing your request. Sorry about that..
        /// </summary>
        public static string AnErrorOccured {
            get {
                return ResourceManager.GetString("AnErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arco.
        /// </summary>
        public static string Area_Arco {
            get {
                return ResourceManager.GetString("Area_Arco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekne.
        /// </summary>
        public static string Area_Ekne {
            get {
                return ResourceManager.GetString("Area_Ekne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fontainebleau.
        /// </summary>
        public static string Area_Fontainebleau {
            get {
                return ResourceManager.GetString("Area_Fontainebleau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frankenjura.
        /// </summary>
        public static string Area_Frankenjura {
            get {
                return ResourceManager.GetString("Area_Frankenjura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joshua Tree National Park.
        /// </summary>
        public static string Area_JoshuaTreeNationalPark {
            get {
                return ResourceManager.GetString("Area_JoshuaTreeNationalPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khao Jeen Lair.
        /// </summary>
        public static string Area_KhaoJeenLair {
            get {
                return ResourceManager.GetString("Area_KhaoJeenLair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuala Lumpur.
        /// </summary>
        public static string Area_KualaLumpur {
            get {
                return ResourceManager.GetString("Area_KualaLumpur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullaberg.
        /// </summary>
        public static string Area_Kullaberg {
            get {
                return ResourceManager.GetString("Area_Kullaberg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sardinia.
        /// </summary>
        public static string Area_Sardinia {
            get {
                return ResourceManager.GetString("Area_Sardinia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siurana.
        /// </summary>
        public static string Area_Siurana {
            get {
                return ResourceManager.GetString("Area_Siurana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tirol.
        /// </summary>
        public static string Area_Tirol {
            get {
                return ResourceManager.GetString("Area_Tirol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yangshuo.
        /// </summary>
        public static string Area_Yangshuo {
            get {
                return ResourceManager.GetString("Area_Yangshuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yosemite National Park.
        /// </summary>
        public static string Area_YosemiteNationalPark {
            get {
                return ResourceManager.GetString("Area_YosemiteNationalPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available parameters.
        /// </summary>
        public static string AvailableParameters {
            get {
                return ResourceManager.GetString("AvailableParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s a list of all available search parameters:.
        /// </summary>
        public static string AvailableParameters_Description {
            get {
                return ResourceManager.GetString("AvailableParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;a href=&quot;{0}&quot; title=&quot;{1}&quot;&gt;better&lt;/a&gt; online guidebook for rock climbers..
        /// </summary>
        public static string BestOnlineGuidebook {
            get {
                return ResourceManager.GetString("BestOnlineGuidebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character casing.
        /// </summary>
        public static string Casing {
            get {
                return ResourceManager.GetString("Casing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climbing.
        /// </summary>
        public static string Climbing {
            get {
                return ResourceManager.GetString("Climbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is the king.
        /// </summary>
        public static string ContentFirst {
            get {
                return ResourceManager.GetString("ContentFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toprope reduces the amount of unnecessary and distracting chrome that stands between you and the actual content making it extremely easy to use the website..
        /// </summary>
        public static string ContentFirst_Body {
            get {
                return ResourceManager.GetString("ContentFirst_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content provided by {0}..
        /// </summary>
        public static string ContentProvidedBy {
            get {
                return ResourceManager.GetString("ContentProvidedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lat,lng.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        public static string Country_Argentina {
            get {
                return ResourceManager.GetString("Country_Argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        public static string Country_Austria {
            get {
                return ResourceManager.GetString("Country_Austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string Country_Canada {
            get {
                return ResourceManager.GetString("Country_Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to England.
        /// </summary>
        public static string Country_England {
            get {
                return ResourceManager.GetString("Country_England", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string Country_France {
            get {
                return ResourceManager.GetString("Country_France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string Country_Germany {
            get {
                return ResourceManager.GetString("Country_Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string Country_Italy {
            get {
                return ResourceManager.GetString("Country_Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        public static string Country_Mexico {
            get {
                return ResourceManager.GetString("Country_Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        public static string Country_Spain {
            get {
                return ResourceManager.GetString("Country_Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string Country_Switzerland {
            get {
                return ResourceManager.GetString("Country_Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        public static string Country_Turkey {
            get {
                return ResourceManager.GetString("Country_Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        public static string Country_UnitedStates {
            get {
                return ResourceManager.GetString("Country_UnitedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular areas.
        /// </summary>
        public static string Discover_MostPopularAreas {
            get {
                return ResourceManager.GetString("Discover_MostPopularAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular countries.
        /// </summary>
        public static string Discover_MostPopularCountries {
            get {
                return ResourceManager.GetString("Discover_MostPopularCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now searching.
        /// </summary>
        public static string Discover_NowSearching {
            get {
                return ResourceManager.GetString("Discover_NowSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found..
        /// </summary>
        public static string Error_404 {
            get {
                return ResourceManager.GetString("Error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find routes.
        /// </summary>
        public static string FindRoutes {
            get {
                return ResourceManager.GetString("FindRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        public static string GPS {
            get {
                return ResourceManager.GetString("GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ewbank.
        /// </summary>
        public static string GradesEwbank {
            get {
                return ResourceManager.GetString("GradesEwbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string GradesFrench {
            get {
                return ResourceManager.GetString("GradesFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YDS.
        /// </summary>
        public static string GradesYDS {
            get {
                return ResourceManager.GetString("GradesYDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use search.
        /// </summary>
        public static string HowToSearch {
            get {
                return ResourceManager.GetString("HowToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple values.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile friendly.
        /// </summary>
        public static string MobileFriendly {
            get {
                return ResourceManager.GetString("MobileFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toprope uses a &lt;i&gt;responsive design&lt;/i&gt; meaning that the website looks great on any device with any screen resolution. Leave your paper guidebooks at home and use Toprope on the go! .
        /// </summary>
        public static string MobileFriendly_Body {
            get {
                return ResourceManager.GetString("MobileFriendly_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate.
        /// </summary>
        public static string Moderate {
            get {
                return ResourceManager.GetString("Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More like these.
        /// </summary>
        public static string MoreResults {
            get {
                return ResourceManager.GetString("MoreResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can narrow down results by only searching for &lt;a href=&quot;{0}&quot;&gt;areas&lt;/a&gt;, &lt;a href=&quot;{1}&quot;&gt;sectors&lt;/a&gt; or &lt;a href=&quot;{2}&quot;&gt;routes&lt;/a&gt;.
        /// </summary>
        public static string NarrowDown {
            get {
                return ResourceManager.GetString("NarrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description.
        /// </summary>
        public static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No related areas found.
        /// </summary>
        public static string NoRelatedAreasFound {
            get {
                return ResourceManager.GetString("NoRelatedAreasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No related sectors found.
        /// </summary>
        public static string NoRelatedSectorsFound {
            get {
                return ResourceManager.GetString("NoRelatedSectorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No routes found.
        /// </summary>
        public static string NoRoutesFound {
            get {
                return ResourceManager.GetString("NoRoutesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found..
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline support.
        /// </summary>
        public static string OfflineSupport {
            get {
                return ResourceManager.GetString("OfflineSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every page that you visit on Toprope automatically becomes available when you don&apos;t have Internet access. This can be extremely useful for those who tend to turn off their mobile data connection when going abroad..
        /// </summary>
        public static string OfflineSupport_Body {
            get {
                return ResourceManager.GetString("OfflineSupport_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches inside area name, description and tags..
        /// </summary>
        public static string Parameter_Area {
            get {
                return ResourceManager.GetString("Parameter_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches for a given type of climbing. Allowed values are &quot;sport&quot; and &quot;trad&quot;..
        /// </summary>
        public static string Parameter_Climbing {
            get {
                return ResourceManager.GetString("Parameter_Climbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches inside the description. For example, &lt;span class=&quot;code&quot;&gt;description:easy&lt;/span&gt; will only include items with the word &quot;easy&quot; in their descriptions..
        /// </summary>
        public static string Parameter_Description {
            get {
                return ResourceManager.GetString("Parameter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches for routes with the given grade. For example, &lt;span class=&quot;code&quot;&gt;grade:5.13a&lt;/span&gt; will only include routes rated 5.13a (7c+)..
        /// </summary>
        public static string Parameter_Grade {
            get {
                return ResourceManager.GetString("Parameter_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricts the search to a given result type. Allowed values are &quot;areas&quot;, &quot;sectors&quot; and &quot;routes&quot;..
        /// </summary>
        public static string Parameter_In {
            get {
                return ResourceManager.GetString("Parameter_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches within 10 kilometers from the given geographical point. For example, &lt;span class=&quot;code&quot;&gt;location:-34.149,18.927&lt;/span&gt; will only include items that are within 10 kilometers from -34.149 (latitude) and 18.927 (longitude)..
        /// </summary>
        public static string Parameter_Location {
            get {
                return ResourceManager.GetString("Parameter_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches inside the name. For example, &lt;span class=&quot;code&quot;&gt;name:cool&lt;/span&gt; will only include items with the word &quot;cool&quot; in their names..
        /// </summary>
        public static string Parameter_Name {
            get {
                return ResourceManager.GetString("Parameter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches inside route name and description..
        /// </summary>
        public static string Parameter_Route {
            get {
                return ResourceManager.GetString("Parameter_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches for the given climbing season. Allowed values are &quot;autumn&quot;, &quot;winter&quot;, &quot;spring&quot; and &quot;summer&quot;..
        /// </summary>
        public static string Parameter_Season {
            get {
                return ResourceManager.GetString("Parameter_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches inside sector name, description and tags..
        /// </summary>
        public static string Parameter_Sector {
            get {
                return ResourceManager.GetString("Parameter_Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches inside the tags. For example, &lt;span class=&quot;code&quot;&gt;tags:spain&lt;/span&gt; will only include items with the tag &quot;span&quot;..
        /// </summary>
        public static string Parameter_Tags {
            get {
                return ResourceManager.GetString("Parameter_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permalink.
        /// </summary>
        public static string Permalink {
            get {
                return ResourceManager.GetString("Permalink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful search.
        /// </summary>
        public static string PowerfulSearch {
            get {
                return ResourceManager.GetString("PowerfulSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;a href=&quot;{0}&quot;&gt;powerful search&lt;/a&gt; allows you to quickly find what you&apos;re looking for. No more clicking around and browsing the endless number of categories. It&apos;s all at your fingertips! .
        /// </summary>
        public static string PowerfulSearch_Body {
            get {
                return ResourceManager.GetString("PowerfulSearch_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range queries.
        /// </summary>
        public static string Ranges {
            get {
                return ResourceManager.GetString("Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related.
        /// </summary>
        public static string Related {
            get {
                return ResourceManager.GetString("Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related areas.
        /// </summary>
        public static string RelatedAreas {
            get {
                return ResourceManager.GetString("RelatedAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To quickly get started, visit the &lt;a href=&quot;{0}&quot;&gt;route directory&lt;/a&gt;..
        /// </summary>
        public static string RouteDirectory_Description {
            get {
                return ResourceManager.GetString("RouteDirectory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route grades.
        /// </summary>
        public static string RouteGrades {
            get {
                return ResourceManager.GetString("RouteGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to routes total.
        /// </summary>
        public static string RoutesTotal {
            get {
                return ResourceManager.GetString("RoutesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search tips.
        /// </summary>
        public static string SearchTips {
            get {
                return ResourceManager.GetString("SearchTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string Seasons {
            get {
                return ResourceManager.GetString("Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors.
        /// </summary>
        public static string Sectors {
            get {
                return ResourceManager.GetString("Sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unnamed.
        /// </summary>
        public static string Unnamed {
            get {
                return ResourceManager.GetString("Unnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unrated.
        /// </summary>
        public static string Unrated {
            get {
                return ResourceManager.GetString("Unrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Toprope, an online guidebook for rock climbers.
        /// </summary>
        public static string WelcomeToToprope {
            get {
                return ResourceManager.GetString("WelcomeToToprope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Toprope?.
        /// </summary>
        public static string WhyToprope {
            get {
                return ResourceManager.GetString("WhyToprope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words and phrases.
        /// </summary>
        public static string WordsAndPhrases {
            get {
                return ResourceManager.GetString("WordsAndPhrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback has been sent..
        /// </summary>
        public static string YourFeedbackHasBeenSent {
            get {
                return ResourceManager.GetString("YourFeedbackHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us improve this page.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
    }
}
